# Generated by Django 5.0.1 on 2024-02-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="floag",
            field=models.ImageField(null=True, upload_to="flags/"),
        ),
    ]
