# Generated by Django 5.0.1 on 2024-02-03 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_country_floag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="floag",
            new_name="flag",
        ),
    ]
