# Generated by Django 5.0.1 on 2024-02-06 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0003_rename_floag_country_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["-created"]},
        ),
    ]
