# Generated by Django 5.0.1 on 2024-02-10 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0005_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["caption"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
    ]
