# Generated by Django 5.0.1 on 2024-01-29 20:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birthdate", models.DateField()),
                ("biography", models.TextField()),
                ("personal_website", models.URLField(blank=True, null=True)),
                ("picture", models.ImageField(upload_to="authors/")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="models.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="models.content",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Insira um ISBN.",
                                regex="^(97(8|9))?\\d{9}(\\d|X)$",
                            )
                        ],
                    ),
                ),
                ("pages", models.PositiveIntegerField()),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("hardcover", "Capa Dura"),
                            ("paperback", "Capa Mole"),
                        ],
                        max_length=10,
                    ),
                ),
                ("author", models.ManyToManyField(to="books.author")),
            ],
            bases=("models.content",),
        ),
    ]
