# Generated by Django 5.0.1 on 2024-02-03 23:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="title", unique=True
            ),
        ),
    ]
