# Generated by Django 5.0.1 on 2024-02-04 12:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                null=True,
                populate_from="<django.db.models.fields.CharField><django.db.models.fields.CharField>",
                unique=True,
            ),
        ),
    ]
