# Generated by Django 5.0.1 on 2024-02-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="authors/"),
        ),
    ]
