# Generated by Django 5.0.1 on 2024-02-06 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="building",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um Código-Postal válido.",
                        regex="^\\d{4}-\\d{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(
                default="user-default.jpg", null=True, upload_to="profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
