# Generated by Django 5.0.1 on 2024-02-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_contact_birthdate_alter_contact_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(
                default="profiles/user-default.jpg", null=True, upload_to="profiles/"
            ),
        ),
    ]
