# Generated by Django 5.0.1 on 2024-02-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_contact_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(
                default="user-default.jpg", null=True, upload_to="profiles/"
            ),
        ),
    ]
