# Generated by Django 5.0.1 on 2024-02-10 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0005_alter_contact_building_alter_contact_district_and_more"),
        ("models", "0006_alter_genre_options_alter_publisher_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateTimeField()),
                ("contents", models.ManyToManyField(to="models.content")),
                (
                    "reader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.reader",
                    ),
                ),
            ],
        ),
    ]
