# Generated by Django 5.0.1 on 2024-02-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requisitions", "0002_alter_requisition_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="is_delivered",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="date_created",
            field=models.DateTimeField(editable=False),
        ),
    ]
