# Generated by Django 5.0.1 on 2024-02-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_alter_requisition_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['-date_created']},
        ),
    ]
