# Generated by Django 5.0.1 on 2024-02-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_contact_building_alter_contact_district_and_more"),
        ("requisitions", "0005_alter_requisition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="Librarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.librarian",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="reader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.reader",
            ),
        ),
    ]
