# Generated by Django 5.0.1 on 2024-02-20 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("requisitions", "0006_requisition_librarian_alter_requisition_reader"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requisition",
            old_name="Librarian",
            new_name="librarian",
        ),
    ]
